/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * A CSV document backed by the massive-csv-core engine.
 *
 * Wraps CsvEditor which itself wraps CsvReader, providing
 * memory-mapped reading, parallel search, edit tracking, and atomic save.
 */
export declare class CsvDocument {
  /** Open a CSV file and return a CsvDocument. */
  static open(path: string): CsvDocument
  /** Get file metadata. */
  getInfo(): CsvInfo
  /** Get a single row (returns edited version if modified). */
  getRow(row: number): Array<string>
  /** Get a range of rows [start, end). Returns edited versions where applicable. */
  getRows(start: number, end: number): Array<Array<string>>
  /** Search for rows matching a query. */
  search(query: string, options?: JsSearchOptions | undefined | null): Array<JsSearchResult>
  /** Edit a single cell. */
  setCell(row: number, col: number, value: string): void
  /** Replace an entire row. */
  setRow(row: number, fields: Array<string>): void
  /** Revert a single row to its original state. */
  revertRow(row: number): void
  /** Revert all pending edits. */
  revertAll(): void
  /** Save all pending edits atomically. */
  save(): void
  /** Number of pending edits. */
  get editCount(): number
  /** Whether there are unsaved changes. */
  get hasChanges(): boolean
}

/** Info about an opened CSV file. */
export interface CsvInfo {
  rowCount: number
  headers: Array<string>
  delimiter: string
  filePath: string
}

/** Options for searching. */
export interface JsSearchOptions {
  column?: string
  caseInsensitive?: boolean
  maxResults?: number
}

/** A single search result returned to JS. */
export interface JsSearchResult {
  rowNum: number
  fields: Array<string>
}
